name: terraform-plan
on:
  pull_request:
    types: [opened]
    branches:
      - '**'
    paths:
      - '**'

env:
  TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  tf-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: clone repository
        uses: actions/checkout@v2

      - name: setup gcloud sdk
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: "nofilter"
          fail_on_error: true

      - name: set up terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.4
          cli_config_credentials_token: ${{ secrets.GCP_TF_TOKEN }}
      
      - name: terraform fmt
        id: fmt
        run: terraform fmt
        continue-on-error: true

      - name: terraform init
        id: init
        run: terraform init

      - name: terraform validate
        id: validate
        run: terraform validate -no-color
        continue-on-error: false

      - name: terraform plan with notification to slack and GitHub
        id: plan
        run: |
          terraform plan -no-color >> result.temp
          cat result.temp | tfnotify --config .tfnotify/github.yml plan --message "$(date)"
          cat result.temp | tfnotify --config .tfnotify/slack.yml plan --message "$(date)"
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL }}
          SLACK_BOT_NAME: tf-notify-bot
          GITHUB_TOKEN: ${{ secrets.github_token }}
        continue-on-error: true

